### ISSUE TITLE
Скласти інтро

### ISSUE THREAD

**Issue by yakovenkon** [yakovenkon/homepage#4]
Скласти інтро (вступ), де в 2-4 реченнях описати, що замовник робить, що подобається робити, що хочеться робити краще, що важливо робити, тощо.

**Comment by volodymyr-kushnir** [comment]
```
<h2>Résumé</h2>
<p>&mdash; I'm the most successful person ever to run for the presidency, by far. Nobody's ever been more successful than me. I'm the most successful person ever to run. Ross Perot isn't successful like me. Romney &mdash; I have a Gucci store that's worth more than Romney. Sorry losers and haters, but my IQ is one of the highest &mdash; and you all know it! Please don't feel so stupid or insecure, it's not your fault.</p>
```

**Comment by yakovenkon** [comment]
<h2>Résumé</h2>
                    <p>&mdash; Hello! I am a junior researcher at the S.P. Tymoshenko Institute of Mechanics of the NAS of Ukraine. I'm the author of the 23 scientific publications, including 2 articles in the foreign journals. My goal is getting a position as a quality assurance engineer.</p>
